version: 2
snapshot:
  widths:
    - 1200
  
  minHeight: 1024
 
  enable-javascript: false
discovery:
  allowedHostnames: []
  networkIdleTimeout: 750
static:
  cleanUrls: false
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
  stripExtensions: false

launch-options:
  headless: true # default
  timeout: 200000 # default
